version: "2"
services: 
    app:
        container_name: testing_node_mongo
        restart: always
        build: .
        ports:
            - "4000:4000"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"